MySql-MVC-CRUD-C--master/Controllers/EmpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_RNWA.Models;

namespace MVC_RNWA.Controllers
{
    public class EmpController : Controller
    {
        // GET: Emp
        CrudEmployee ci = new CrudEmployee();
        public ActionResult Index()
        {
            ModelState.Clear();
            return View(ci.GetEmp());
        }

        // GET: Emp/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Emp/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Emp/Create
        [HttpPost]
        public ActionResult Create(CrudEmp empinser)
        {

            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    if (ci.insertemp(empinser))
                    {
                        ViewBag.message = "Uspjesno dodan novi djelatnik";
                        ModelState.Clear();
                    }
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Emp/Edit/5
        public ActionResult Edit(int id)
        {
            return View(ci.GetEmp().Find(itemodel => itemodel.employeeNumber == id));
        }

        // POST: Emp/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, CrudEmp edittemp)
        {
            try
            {
                ci.editemp(edittemp);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Emp/Delete/5
        public ActionResult Delete(int id)
        {
            ci.deleteemp(id);

            return RedirectToAction("Index");
        }

        // POST: Emp/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MySql-MVC-CRUD-C--master/Controllers/ProdController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_RNWA.Models;

namespace MVC_RNWA.Controllers
{
    public class ProdController : Controller
    {
        // GET: Prod

        CrudImplementation ci = new CrudImplementation();
        public ActionResult Index()
        {
            ModelState.Clear();
            return View(ci.GetProd());
        }

        // GET: Prod/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Prod/Create
        [HttpGet]

        public ActionResult Create()
        {
            return View();
        }

        // POST: Prod/Create
        [HttpPost]
        public ActionResult Create(CrudProp prodinsert)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    if (ci.insertprod(prodinsert))
                    {
                        ViewBag.message = "Uspjesno dodan proizvod";
                        ModelState.Clear();
                    }
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Prod/Edit/5
        public ActionResult Edit(string id)
        {
            return View(ci.GetProd().Find(itemodel=>itemodel.productCode==id));
        }

        // POST: Prod/Edit/5
        [HttpPost]
        public ActionResult Edit(string id, CrudProp updateprod)
        {
            try
            {
                ci.editprod(updateprod);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Prod/Delete/5
        public ActionResult Delete(string id)
        {
            ci.deleteprod(id);

            return RedirectToAction("Index");
        }

        // POST: Prod/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MySql-MVC-CRUD-C--master/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CRUD ZADAĆA</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MVC-CRUD", "Index", "Prod", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Proizvodi", "Index", "Prod")</li>
                    <li>@Html.ActionLink("Uposleni", "Index", "Emp")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Frano-Vedran CRUD</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>